mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^doublesyllable/', include('DoubleSyllable.urls')),
    url(r'^s_word/', include('s_word.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

mysite/s_word/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^word/$', views.word, name='word'),
    url(r'^test/$', views.test, name='test'),
    url(r'^errortest/$', views.errortest, name='errortest'),
    url(r'^randomtest/$', views.randomtest, name='randomtest'),
    url(r'^reviewtest/$', views.reviewtest, name='reviewtest'),
    url(r'^reviewtest2/$', views.reviewtest2, name='reviewtest2'),
    url(r'^(?P<word_id>[0-9]+)/result/$', views.result, name='result'),
    url(r'^(?P<word_id>[0-9]+)/reviewresult/$', views.reviewresult, name='reviewresult'),
]

mysite/s_word/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
# 实词
class Word(models.Model):
    sword = models.CharField(max_length=4)

    class Meta:
        managed = False
        db_table = "t_sword"

# 一个实词有多种含义
class SWordMeaning(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    pinyin = models.CharField(max_length=4,default="")
    word_class = models.CharField(max_length=10)
    meaning = models.CharField(max_length=100)
    difficulty = models.IntegerField(default=0)

    class Meta:
        managed = False
        db_table = "t_swordmeaning"

# 例句：每种含义有一到多个例句
@python_2_unicode_compatible 
class SWord(models.Model):
    sword = models.CharField(max_length=4)
    pinyin = models.CharField(max_length=4,default="")
    word_class = models.CharField(max_length=10)
    meaning = models.CharField(max_length=100)
    sample = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    translation = models.CharField(max_length=100)
    swordmeaning = models.ForeignKey(SWordMeaning, on_delete=models.CASCADE, default="")

    def __str__(self):
        return self.sword

# 每个例句可以出多道题（三种题型：含义，词性，拼音），学习阶段用的测试题
class Question(models.Model):
    sword = models.ForeignKey(SWord, on_delete=models.CASCADE)
    test_type = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = "t_question"

# 每道题有多个选项
class SWordTest1Choice(models.Model):
    sword = models.ForeignKey(SWord, on_delete=models.CASCADE)
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    test_type = models.CharField(max_length=10)
    choice_txt = models.CharField(max_length=100)
    is_correct = models.IntegerField(default=0)

# word related question count
class SWordQuestionByWord(models.Model):
    sword = models.CharField(max_length=100)
    questioncount = models.IntegerField(default=0)

    class Meta:
        managed = False
        db_table = "v_swordtestquestion_count"

# user passed word count
class SWordUserQuestionByWord(models.Model):
    sword = models.CharField(max_length=100)
    questioncount = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    passedcount = models.IntegerField(default=0)
    status = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = "v_user_passed_question_count"

# 每道预习题的测试结果历史
class SWordTest(models.Model):
    sword = models.ForeignKey(SWord, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    test_date = models.DateTimeField('test accessed')
    test_result = models.IntegerField(default=0)
    test_answer = models.CharField(max_length=100,default="")
    test_type = models.CharField(max_length=10)

# 用户每个实词的测试通过情况（根据含义选例句）
class SWordReviewRound(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    review_round = models.IntegerField(default=0)
    test_date = models.DateTimeField('test accessed')
    score = models.IntegerField(default=0)
    duration = models.FloatField(default=0)
    test_count = models.IntegerField(default=0)

# v_user_review_round_1_summary
class SWordReviewRound1View(models.Model):
    sword = models.CharField(max_length=100)
    user_id = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    test_date = models.DateTimeField('test accessed')
    status = models.CharField(max_length=100)
    till_now = models.FloatField(default=0)
    test_count = models.IntegerField(default=0)
    avg_score = models.FloatField(default=0)

    class Meta:
        managed = False
        db_table = "v_user_review_round_1_summary"

# v_user_review_round_2_summary
class SWordReviewRound2View(models.Model):
    sword = models.CharField(max_length=100)
    user_id = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    test_date = models.DateTimeField('test accessed')
    status = models.CharField(max_length=100)
    till_now = models.FloatField(default=0)
    test_count = models.IntegerField(default=0)
    avg_score = models.FloatField(default=0)
    duration = models.FloatField(default=0)

    class Meta:
        managed = False
        db_table = "v_user_review_round_2_summary"

# 错题排序
class SWordTestScore(models.Model):
    sword_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    test_type = models.CharField(max_length=10)
    score = models.FloatField(default=0)

    class Meta:
        managed = False
        db_table = "v_user_question_score"

# 随机题（从通过的题中选）
class SWordPassedQuestion(models.Model):
    sword_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    test_type = models.CharField(max_length=10)
    sword = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = "v_user_passed_question"

mysite/s_word/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from .models import SWord,SWordTest,SWordTest1Choice,SWordUserQuestionByWord,SWordQuestionByWord,SWordTestScore,Question,SWordPassedQuestion,Word,SWordMeaning,SWordReviewRound,SWordReviewRound1View,SWordReviewRound2View
from django.http import HttpResponse
from django.template import loader
from django.utils import timezone
from django.conf import settings
from django.shortcuts import redirect
from django.db.models import Avg, F, Max, Min, Case, When, Sum, Count
from django.db import models
import random

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    current_user = request.user

    # get inprogress or passed word list
    start_word_list = SWordUserQuestionByWord.objects.filter(user_id=current_user.id)
    inprogress_word_list = start_word_list.filter(status="inprogress")

    # get not start word list
    notstart_word_list = SWordQuestionByWord.objects.exclude(id__in=start_word_list)

    # get round 1 review word list
    round1_list = SWordReviewRound1View.objects.filter(user_id=current_user.id)

    # get round 2 review word list
    round2_list = SWordReviewRound2View.objects.filter(user_id=current_user.id)

    # prepare return page
    template = loader.get_template('s_word/index.html')
    context = {
        'inprogress_word_list': inprogress_word_list,
        'notstart_word_list': notstart_word_list,
        'round1_list':round1_list,
        'round2_list':round2_list,
        'user': current_user.username,
    }
    # return page
    return HttpResponse(template.render(context, request))

def word(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    sword = request.GET.get('sword', '')
    sword_list = SWord.objects.filter(sword=sword)

    pinyin_questions = SWordTest1Choice.objects.filter(sword_id__in=sword_list, test_type='拼音').values('sword_id').distinct().count()
    word_class_questions = SWordTest1Choice.objects.filter(sword_id__in=sword_list, test_type='词性').values('sword_id').distinct().count()
    meaning_questions = SWordTest1Choice.objects.filter(sword_id__in=sword_list, test_type='含义').values('sword_id').distinct().count()

    pinyin_passed = SWordTest.objects.filter(sword_id__in=sword_list, test_type='拼音', user_id=request.user.id, test_result=1).values('sword_id').distinct().count()
    word_class_passed = SWordTest.objects.filter(sword_id__in=sword_list, test_type='词性', user_id=request.user.id, test_result=1).values('sword_id').distinct().count()
    meaning_passed = SWordTest.objects.filter(sword_id__in=sword_list, test_type='含义', user_id=request.user.id, test_result=1).values('sword_id').distinct().count()

    sword_list= sword_list.annotate(failcount=Count(Case(When(swordtest__user_id=request.user.id,swordtest__test_result=0,then=F('swordtest__test_result')),output_field=models.IntegerField())),
                                    passcount=Count(Case(When(swordtest__user_id=request.user.id,swordtest__test_result=1,then=F('swordtest__test_result')),output_field=models.IntegerField())))

    if pinyin_questions == 0:
        pinyin_test_status = "notest"
    elif pinyin_questions == pinyin_passed:
        pinyin_test_status = "passed"
    elif pinyin_passed == 0:
        pinyin_test_status = "notstart"
    else: 
        pinyin_test_status = "inprogress"

    if word_class_questions == 0:
        word_class_test_status = "notest"
    elif word_class_questions == word_class_passed:
        word_class_test_status = "passed"
    elif word_class_passed == 0:
        word_class_test_status = "notstart"
    else:
        word_class_test_status = "inprogress"

    if meaning_questions == 0:
        meaning_test_status = "notest"
    elif meaning_questions == meaning_passed:
        meaning_test_status = "passed"
    elif meaning_passed == 0:
        meaning_test_status = "notstart"
    else: 
        meaning_test_status = "inprogress"

    # prepare return page
    template = loader.get_template('s_word/word.html')
    context = {
        'sword': sword,
        'sword_list': sword_list,
        'user': request.user.username,
        'pinyin_test_status': pinyin_test_status,
        'word_class_test_status': word_class_test_status,
        'meaning_test_status': meaning_test_status
    }
    # return page
    return HttpResponse(template.render(context, request))

def test(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    sword = request.GET.get('sword', '')
    test_type = request.GET.get('test_type', '')
    word_list = SWord.objects.filter(sword=sword)

    # prepare return page
    template = loader.get_template('s_word/test.html')
    context = {
        'sword': sword,
        'word_list': word_list,
        'user': request.user.username,
        'test_type': test_type
    }
    # return page
    return HttpResponse(template.render(context, request))

def reviewtest(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    sword = request.GET.get('sword', '')
    word_id = Word.objects.filter(sword=sword)[0].id
    question_list = SWordMeaning.objects.filter(word_id=word_id)
    choice_list = SWord.objects.filter(sword=sword)

    # prepare return page
    template = loader.get_template('s_word/reviewtest.html')
    context = {
        'sword': sword,
        'question_list': question_list,
        'choice_list': choice_list,
        'user': request.user.username
    }
    # return page
    return HttpResponse(template.render(context, request))

def reviewtest2(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    sword = request.GET.get('sword', '')
    word_id = Word.objects.filter(sword=sword)[0].id
    meaning_list = SWordMeaning.objects.filter(word_id=word_id)
    choice_list = SWord.objects.filter(sword=sword)

    # prepare return page
    template = loader.get_template('s_word/reviewtest2.html')
    context = {
        'sword': sword,
        'meaning_list': meaning_list,
        'choice_list': choice_list,
        'user': request.user.username
    }
    # return page
    return HttpResponse(template.render(context, request))

def errortest(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    lowest_score_list = SWordTestScore.objects.filter(user_id=request.user.id, score__lt=0).values('id')[:10]

    question_list = Question.objects.filter(id__in=lowest_score_list)

    # prepare return page
    template = loader.get_template('s_word/errortest.html')
    context = {
        'question_list': question_list,
        'user': request.user.username,
        'title': "错题练习"
     }
    # return page
    return HttpResponse(template.render(context, request))

def randomtest(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    q_ids = SWordPassedQuestion.objects.filter(user_id=request.user.id).values('id').order_by('?')[0:10]
    question_list = Question.objects.filter(id__in=q_ids)

    # prepare return page
    template = loader.get_template('s_word/errortest.html')
    context = {
        'question_list': question_list,
        'user': request.user.username,
        'title': "随机练习"
     }
    # return page
    return HttpResponse(template.render(context, request))

def result(request, word_id):
    sword = get_object_or_404(SWord, pk=word_id)
    # record test result to db
    SWordTest.objects.create(user_id=request.user.id,
                                      sword_id=word_id,
                                      test_date=timezone.now(),
                                      test_type=request.POST.get("test_type", ""),
                                      test_result=request.POST.get("test_result", ""),
                                      test_answer=request.POST.get("test_answer", "")
                                      )
    # return page 
    return HttpResponse("test result is recorded")

def reviewresult(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    # record test result to db
    SWordReviewRound.objects.create(user_id=request.user.id,
                                      word_id=word_id,
                                      review_round = request.POST.get("round", 0), 
                                      test_date=timezone.now(),
                                      score=request.POST.get("score", 0),
                                      duration=request.POST.get("duration", 0),
                                      test_count=request.POST.get("test_count", 0),
                                      )
    # return page 
    return HttpResponse("test result is recorded")

mysite/s_word/templates/s_word/index.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Sword Dashboard</title>
  <style type="text/css">

    @import url(https://fonts.googleapis.com/css?family=Work+Sans:300,600);

    body{
      font-size: 20px;
      font-family: 'Work Sans', sans-serif;
      color: #333;
      font-weight: 300;
      text-align: center;
      background-color: #f8f6f0;
    }
    h1{
      font-weight: 300;
      margin: 0px;
      padding: 10px;
      font-size: 20px;
      background-color: #444;
      color: #fff;
    }
    .question{
      font-size: 30px;
      margin-bottom: 10px;
    }
    .answers {
      margin-bottom: 20px;
      text-align: left;
      display: inline-block;
    }
    .answers label{
      display: block;
      margin-bottom: 10px;
    }
    button{
      font-family: 'Work Sans', sans-serif;
      font-size: 22px;
      background-color: #279;
      color: #fff;
      border: 0px;
      border-radius: 3px;
      padding: 20px;
      cursor: pointer;
      margin-bottom: 20px;
    }
    button:hover{
      background-color: #38a;
    }

    .passed {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    }

    .perfect_passed {
    background-color: darkgreen;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    }

    .notstart {
    background-color: gray;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    }

    .start_later {
    background-color: gray;
    border: none;
    color: gray;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    }

    .inprogress {
    background-color: orange;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    }

    .inprogress_later {
    background-color: orange;
    border: none;
    color: orange;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    }

    .slide{
      position: absolute;
      left: 0px;
      top: 0px;
      width: 100%;
      z-index: 1;
      opacity: 0;
      transition: opacity 0.5s;
    }
    .active-slide{
      opacity: 1;
      z-index: 2;
    }
    .quiz-container{
      position: relative;
      height: 400px;
      margin-top: 20px;
    }


  </style>
</head>
<body>
    <p>用户：{{ user }}</p>
    <h1>实词学习: 复习第二轮</h1>
    {% for word in round2_list %}
    <a href="/s_word/reviewtest2/?sword={{ word.sword }}" class={{ word.status }}>
      <b>{{ word.sword }}</b>
      <br>日期：{{ word.till_now|default_if_none:"0"|floatformat:0 }}天
      <br>平均分数：{{ word.avg_score|floatformat:0|default_if_none:"" }}
      <br>测试次数：{{ word.test_count|default_if_none:"0" }}
      <br>每题用时：{{ word.duration|floatformat:0|default_if_none:"" }}秒
    </a>
    {% endfor %}
    <h1>实词学习: 复习第一轮</h1>
    {% for word in round1_list %}
    <a href="/s_word/reviewtest/?sword={{ word.sword }}" class={{ word.status }}>
      <b>{{ word.sword }}</b>
      <br>日期：{{ word.till_now|default_if_none:"0"|floatformat:0 }}天
      <br>平均分数：{{ word.avg_score|floatformat:0|default_if_none:"" }}
      <br>测试次数：{{ word.test_count|default_if_none:"0" }}
    </a>
    {% endfor %}
    <a href="/s_word/errortest/">错题测试</a>
    <a href="/s_word/randomtest/">随机测试</a>
    <h1>实词学习: 预习进行中</h1>
    {% for word in inprogress_word_list %}
    <a href="/s_word/word/?sword={{ word.sword }}" class={{ word.status }}>{{ word.sword }}<br>{{ word.passedcount }}/{{ word.questioncount }}</a>
    {% endfor %}
    <h1>实词学习: 未开始</h1>
    {% for word in notstart_word_list %}
    <a href="/s_word/word/?sword={{ word.sword }}" class=notstart>{{ word.sword }}<br>0/{{ word.questioncount }}</a>
    {% endfor %}
    <h1>其他学习内容</h1>
    <a href="/doublesyllable/">双音词学习</a>

</body>
</html>

mysite/s_word/templates/s_word/test.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Sword Preview</title>
  <style type="text/css">

    @import url(https://fonts.googleapis.com/css?family=Work+Sans:300,600);

    body{
      font-size: 20px;
      font-family: 'Work Sans', sans-serif;
      color: #333;
      font-weight: 300;
      text-align: center;
      background-color: #f8f6f0;
    }
    h1{
      font-weight: 300;
      margin: 0px;
      padding: 10px;
      font-size: 20px;
      background-color: #444;
      color: #fff;
    }
    .question{
      font-size: 30px;
      margin-bottom: 10px;
    }
    .answers {
      margin-bottom: 20px;
      text-align: left;
      display: inline-block;
    }
    .answers label{
      display: block;
      margin-bottom: 10px;
    }
    button{
      font-family: 'Work Sans', sans-serif;
      font-size: 22px;
      background-color: #279;
      color: #fff;
      border: 0px;
      border-radius: 3px;
      padding: 20px;
      cursor: pointer;
      margin-bottom: 20px;
    }
    button:hover{
      background-color: #38a;
    }

    .slide{
      position: absolute;
      left: 0px;
      top: 0px;
      width: 100%;
      z-index: 1;
      opacity: 0;
      transition: opacity 0.5s;
    }
    .active-slide{
      opacity: 1;
      z-index: 2;
    }
    .quiz-container{
      position: relative;
      height: 560px;
      margin-top: 20px;
    }


  </style>
</head>

<body>
{% load shuffle %}
{% if word_list %}
<h1>{{ test_type }}：<b>{{ sword }}</b></h1>
<div class="quiz-container">
  <div id="quiz"></div>
</div>
<button id="previous">上一题</button>
<button id="submit">检查答案</button>
<button id="next">下一题</button>
<a href="/s_word/word/?sword={{ sword }}">返回</a>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">

  (function() {
    const myQuestions = [
    {% for word in word_list %}
    {% for wquestion in word.question_set.all|shuffle %}
      {% if wquestion.test_type == test_type %}
      {
        question: "{{ word.sample|linebreaksbr }} <br><small> {{ word.source|linebreaksbr }} </small>",
        answers: [
          {% for choice in wquestion.swordtest1choice_set.all|shuffle %}
            [{{ choice.id }}, "{{ choice.choice_txt|linebreaksbr }}"],
          {% endfor %}
        ],
        {% for choice in wquestion.swordtest1choice_set.all %}
          {% if choice.is_correct %}
        correctAnswer: "{{ choice.id }}",
          {% endif %}
        {% endfor %}
        translation: "{{ word.translation|linebreaksbr }}",
        highlight: "{{ word.sword|linebreaksbr }}",
        id: "{{ word.id }}",
        question_id: "{{ wquestion.id }}"
      },
      {% endif %}
    {% endfor %}
    {% endfor %}
    ];

    function initSubmitResultForm() {
      myQuestions.forEach((currentQuestion, questionNumber) => {
        $('#testresultform'+questionNumber).submit(function(e) {

        e.preventDefault(); // avoid to execute the actual submit of the form.

        var form = $(this);
        var url = form.attr('action');

        $.ajax({
              method: "POST",
              url: url,
              data: form.serialize(), // serializes the form's elements.
              }).done(function(data)
              {
                console.log('Submission was successful.');
                console.log(data);
              }).fail(function (data) {
                console.log('An error occurred.');
                console.log(data);
              });
        });
      });
    }

    function buildQuiz() {
      // we'll need a place to store the HTML output
      const output = [];

      // for each question...
      myQuestions.forEach((currentQuestion, questionNumber) => {
        // we'll want to store the list of answer choices
        const answers = [];

        // and for each available answer...
        currentQuestion.answers.forEach((currentAnswer, answerNumber) => {
          // ...add an HTML radio button
          answers.push(
            `<label>
              <input type="radio" name="question${questionNumber}" value="${currentAnswer[0]}">
                ${currentAnswer[1]}
            </label>`
          );
        });

        // add this question and its answers to the output
        var re = new RegExp(currentQuestion.highlight,"g")
        var replace_txt = "<b>$&</b>"
        var question_txt = currentQuestion.question.replace(re, replace_txt )
        output.push(
          `<div class="slide">
            <div id="results${questionNumber}"></div>
            第${questionNumber+1}/${myQuestions.length}题
            <div class="question"> ${question_txt} </div>
            <div class="answers"> ${answers.join("")} </div>
            <div class="translation" style="color:#f8f6f0"> 翻译：${currentQuestion.translation} </div>
            <form id="testresultform${questionNumber}" action="/s_word/${currentQuestion.id}/result/" method="post">
                {% csrf_token %}
                <input type='hidden' name="test_type" value="{{ test_type }}" />
                <input type='hidden' name="test_answer" value="" />
                <input type='hidden' name="test_result" value="" />
                <input type='hidden' name="question_id_id" value=${currentQuestion.question_id} />
            </form>
            
          </div>`
        );
      });

      // finally combine our output list into one string of HTML and put it on the page
      quizContainer.innerHTML = output.join("");
    }

    function showResults() {
      // gather answer containers from our quiz
      const answerContainers = quizContainer.querySelectorAll(".answers");
      // gather translation container from our quiz
      const translationContainers = quizContainer.querySelectorAll(".translation");

      // keep track of user's answers
      let numCorrect = 0;

      // for each question...
      questionNumber = currentSlide;
      currentQuestion = myQuestions[questionNumber];
      
        // find selected answer
        const resultsContainer = document.getElementById(`results${questionNumber}`);
        const answerContainer = answerContainers[questionNumber];
        const selector = `input[name=question${questionNumber}]:checked`;
        const userAnswer = (answerContainer.querySelector(selector) || {}).value;
        var is_correct = 0

        // if answer is correct
        if (userAnswer === currentQuestion.correctAnswer) {
          // add to the number of correct answers
          numCorrect++;

          // color the answers green
          answerContainers[questionNumber].style.color = "green";
          translationContainers[questionNumber].style.color = "green";
          //
          is_correct = 1
        } else {
          // if answer is wrong or blank
          // color the answers red
          answerContainers[questionNumber].style.color = "red";
          translationContainers[questionNumber].style.color = "red";
        }

        // set test result form data
        document.getElementsByName('test_answer')[questionNumber].value = userAnswer
        document.getElementsByName('test_result')[questionNumber].value = is_correct

        // submit test result to server
        
        $('#testresultform'+questionNumber).submit();

        // show current slide's answer is correct or not
        if (is_correct === 1) {
          resultsContainer.innerHTML = `<font color=green>回答正确</font>`;
        } else {
          resultsContainer.innerHTML = `<font color=red>回答错误</font>`;
        };
      
    }

    function showSlide(n) {
      slides[currentSlide].classList.remove("active-slide");
      slides[n].classList.add("active-slide");
      currentSlide = n;

      if (currentSlide === 0) {
        previousButton.style.display = "none";
      } else {
        previousButton.style.display = "inline-block";
      }

      if (currentSlide === slides.length - 1) {
        nextButton.style.display = "none";
      } else {
        nextButton.style.display = "inline-block";
      }
    }

    function showNextSlide() {
      showSlide(currentSlide + 1);
    }

    function showPreviousSlide() {
      showSlide(currentSlide - 1);
    }

    const quizContainer = document.getElementById("quiz");
    const submitButton = document.getElementById("submit");

    // display quiz right away
    buildQuiz();
    initSubmitResultForm();

    const previousButton = document.getElementById("previous");
    const nextButton = document.getElementById("next");
    const slides = document.querySelectorAll(".slide");
    let currentSlide = 0;

    showSlide(0);

    // on submit, show results
    submitButton.addEventListener("click", showResults);
    previousButton.addEventListener("click", showPreviousSlide);
    nextButton.addEventListener("click", showNextSlide);
  })();


</script>
{% else %}
    <p>该实词目前没有学习内容.</p>
    <a href="/s_word/word/?sword={{ sword }}">返回</a>
{% endif %}
</body>

</html>