mysite/DoubleSyllable/urls.py
from django.conf.urls import url

from . import views

app_name = 'DoubleSyllable'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^preview/$', views.preview, name='preview'),
    url(r'^review/$', views.review, name='review'),
    url(r'^review2/$', views.review2, name='review2'),
    url(r'^(?P<doublesyllable_id>[0-9]+)/result/$', views.result, name='result'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^doublesyllable/', include('DoubleSyllable.urls')),
    url(r'^s_word/', include('s_word.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

mysite/DoubleSyllable/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible

# Create your models  here.
@python_2_unicode_compatible
class DoubleSyllable(models.Model):
    word = models.CharField(max_length=10)
    classical = models.CharField(max_length=100)
    current = models.CharField(max_length=100)
    sample = models.CharField(max_length=120)
    translation = models.CharField(max_length=200)
    source = models.CharField(max_length=50)
    
    def __str__(self):
        return self.word

class DoubleSyllableTestChoice(models.Model):
    doublesyllable = models.ForeignKey(DoubleSyllable, on_delete=models.CASCADE)
    choice_txt = models.CharField(max_length=100)
    is_correct = models.IntegerField(default=0)

class DoubleSyllableAccess(models.Model):
    doublesyllable = models.ForeignKey(DoubleSyllable, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    access_date = models.DateTimeField('date accessed')

class DoubleSyllableTest(models.Model):
    doublesyllable = models.ForeignKey(DoubleSyllable, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    test_date = models.DateTimeField('test accessed')
    test_result = models.IntegerField(default=0)
    test_answer = models.CharField(max_length=100,default="")

mysite/DoubleSyllable/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from .models import DoubleSyllable
from .models import DoubleSyllableAccess
from .models import DoubleSyllableTestChoice
from .models import DoubleSyllableTest
from django.http import HttpResponse
from django.template import loader
from django.utils import timezone
from django.conf import settings
from django.shortcuts import redirect

# Create your views here.
def preview(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))

    current_user = request.user
    total_words = DoubleSyllable.objects.count()
    
    # already acessed word list
    accessed_word_list = DoubleSyllableAccess.objects.filter(user_id__exact=current_user.id).values('doublesyllable_id').distinct()
    accessed_words = accessed_word_list.count()

    # fetch one unaccessed word 
    if total_words != accessed_words:
        word = DoubleSyllable.objects.exclude(id__in=accessed_word_list).values('word')[0]
        # fetch work list by word
        word_list = DoubleSyllable.objects.filter(word__exact=word['word'])
    else:
        word_list = None
    
    template = loader.get_template('DoubleSyllable/preview.html')
    context = {
        'word_list': word_list,
        'total_words': total_words,
        'accessed_words': accessed_words,
        'title': '预习',
        'hide_next_word': False
    }
    # return response
    return HttpResponse(template.render(context, request))

def review(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))

    current_user = request.user
    accessed_words_list = DoubleSyllableAccess.objects.filter(user_id__exact=current_user.id).values('doublesyllable_id').distinct()
    accessed_words = accessed_words_list.count()
    
    # already passed word list
    passed_word_list = DoubleSyllableTest.objects.filter(user_id__exact=current_user.id,test_result=1).values('doublesyllable_id').distinct()
    passed_words = passed_word_list.count()

    # get unpassed word list
    unpassed_word_list = accessed_words_list.difference(passed_word_list)

    # fetch one unpassed word 
    if accessed_words != passed_words:
        word = DoubleSyllable.objects.filter(id__in=unpassed_word_list).values('word')[0]
        # fetch work list by word
        word_list = DoubleSyllable.objects.filter(word__exact=word['word'])
    else:
        word_list = None

    template = loader.get_template('DoubleSyllable/preview.html')
    context = {
        'word_list': word_list,
        'total_words': accessed_words,
        'accessed_words': passed_words,
        'title': '复习未通过词语',
        'hide_next_word': False
    }
    # return response
    return HttpResponse(template.render(context, request))

def review2(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))

    current_user = request.user
    error_words_list = DoubleSyllableTest.objects.filter(user_id__exact=current_user.id,test_result=0).values('doublesyllable_id').distinct()
    error_words = error_words_list.count()
    
    if error_words != 0:
        word_list = DoubleSyllable.objects.filter(id__in=error_words_list)
    else:
        word_list = None

    template = loader.get_template('DoubleSyllable/preview.html')
    context = {
        'word_list': word_list,
        'total_words': error_words,
        'accessed_words': error_words,
        'title': '复习曾出错词语',
        'hide_next_word': True
    }
    # return response
    return HttpResponse(template.render(context, request))

def index(request):
    if not request.user.is_authenticated:
        return redirect('/admin/login?next=%s' % (request.path))
    
    current_user = request.user
    # total word
    total_words = DoubleSyllable.objects.count()
    
    # already acessed word count
    accessed_words = DoubleSyllableAccess.objects.filter(user_id__exact=current_user.id).values('doublesyllable_id').distinct().count()

    # pass test word count
    passed_words = DoubleSyllableTest.objects.filter(user_id__exact=current_user.id,test_result=1).values('doublesyllable_id').distinct().count()

    # prepare return page
    template = loader.get_template('DoubleSyllable/index.html')
    context = {
        'total_words': total_words,
        'accessed_words': accessed_words,
        'passed_words': passed_words,
        'user': current_user.username
    }
    # return page
    return HttpResponse(template.render(context, request))

def result(request, doublesyllable_id):
    doublesyllable = get_object_or_404(DoubleSyllable, pk=doublesyllable_id)
    # record test result to db
    DoubleSyllableTest.objects.create(user_id=request.user.id,
                                      doublesyllable_id=doublesyllable_id,
                                      test_date=timezone.now(),
                                      test_result=request.POST.get("test_result", ""),
                                      test_answer=request.POST.get("test_answer", "")
                                      )
    # record access log to db
    DoubleSyllableAccess.objects.create(user_id=request.user.id,
                                        doublesyllable_id=doublesyllable_id,
                                        access_date=timezone.now()
                                        )
    # return page 
    return HttpResponse("test result is recorded")

mysite/DoubleSyllable/templates/DoubleSyllable/index.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Double Syllable Preview</title>
  <style type="text/css">

    @import url(https://fonts.googleapis.com/css?family=Work+Sans:300,600);

    body{
      font-size: 20px;
      font-family: 'Work Sans', sans-serif;
      color: #333;
      font-weight: 300;
      text-align: center;
      background-color: #f8f6f0;
    }
    h1{
      font-weight: 300;
      margin: 0px;
      padding: 10px;
      font-size: 20px;
      background-color: #444;
      color: #fff;
    }
    .question{
      font-size: 30px;
      margin-bottom: 10px;
    }
    .answers {
      margin-bottom: 20px;
      text-align: left;
      display: inline-block;
    }
    .answers label{
      display: block;
      margin-bottom: 10px;
    }
    button{
      font-family: 'Work Sans', sans-serif;
      font-size: 22px;
      background-color: #279;
      color: #fff;
      border: 0px;
      border-radius: 3px;
      padding: 20px;
      cursor: pointer;
      margin-bottom: 20px;
    }
    button:hover{
      background-color: #38a;
    }





    .slide{
      position: absolute;
      left: 0px;
      top: 0px;
      width: 100%;
      z-index: 1;
      opacity: 0;
      transition: opacity 0.5s;
    }
    .active-slide{
      opacity: 1;
      z-index: 2;
    }
    .quiz-container{
      position: relative;
      height: 400px;
      margin-top: 20px;
    }


  </style>
</head>
<body>
    <h1>双音词学习</h1>
    <p>用户：{{ user }}</p>
    <p>已学词语：{{ accessed_words }}/{{ total_words }} </p>
    <p>已通过词语：{{ passed_words }}/{{ total_words }} </p>
    <a href="/doublesyllable/preview">预习未学词语</a>
    <a href="/doublesyllable/review">复习未通过词语</a>
    <a href="/doublesyllable/review2">复习曾出错词语</a>
</body>
</html>

mysite/DoubleSyllable/templates/DoubleSyllable/preview.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Double Syllable Preview</title>
  <style type="text/css">

    @import url(https://fonts.googleapis.com/css?family=Work+Sans:300,600);

    body{
      font-size: 20px;
      font-family: 'Work Sans', sans-serif;
      color: #333;
      font-weight: 300;
      text-align: center;
      background-color: #f8f6f0;
    }
    h1{
      font-weight: 300;
      margin: 0px;
      padding: 10px;
      font-size: 20px;
      background-color: #444;
      color: #fff;
    }
    .question{
      font-size: 30px;
      margin-bottom: 10px;
    }
    .answers {
      margin-bottom: 20px;
      text-align: left;
      display: inline-block;
    }
    .answers label{
      display: block;
      margin-bottom: 10px;
    }
    button{
      font-family: 'Work Sans', sans-serif;
      font-size: 22px;
      background-color: #279;
      color: #fff;
      border: 0px;
      border-radius: 3px;
      padding: 20px;
      cursor: pointer;
      margin-bottom: 20px;
    }
    button:hover{
      background-color: #38a;
    }





    .slide{
      position: absolute;
      left: 0px;
      top: 0px;
      width: 100%;
      z-index: 1;
      opacity: 0;
      transition: opacity 0.5s;
    }
    .active-slide{
      opacity: 1;
      z-index: 2;
    }
    .quiz-container{
      position: relative;
      height: 400px;
      margin-top: 20px;
    }


  </style>
</head>

<body>
{% load shuffle %}
{% if word_list and total_words %}
{% if accessed_words != total_words %}
<p> {{ title }}进度: {{ accessed_words|add:1 }}/{{ total_words  }}
{% endif %}
<h1>双音词自测：<b>{{ word_list.0.word }}</b></h1>
<div id="results"></div>
<div class="quiz-container">
  <div id="quiz"></div>
</div>
<button id="previous">上一题</button>
<button id="next">下一题</button>
<button id="submit">提交答案</button>
<button id="nextword">下一词</button>
<a href="/doublesyllable/">返回</a>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">

  (function() {
    const myQuestions = [
    {% for word in word_list %}
      {
        question: "{{ word.sample|linebreaksbr }} <br><small> {{ word.source|linebreaksbr }} </small>",
        answers: [
          {% for choice in word.doublesyllabletestchoice_set.all|shuffle %}
          [{{ choice.id }}, "{{ choice.choice_txt|linebreaksbr }}"],
          {% endfor %}
        ],
        {% for choice in word.doublesyllabletestchoice_set.all %}
          {% if choice.is_correct %}
        correctAnswer: "{{ choice.id }}",
          {% endif %}
        {% endfor %}
        translation: "{{ word.translation|linebreaksbr }}",
        highlight: "{{ word.word|linebreaksbr }}",
        id: "{{ word.id }}"
      },
    {% endfor %}
    ];

    function buildQuiz() {
      // we'll need a place to store the HTML output
      const output = [];

      // for each question...
      myQuestions.forEach((currentQuestion, questionNumber) => {
        // we'll want to store the list of answer choices
        const answers = [];

        // and for each available answer...
        currentQuestion.answers.forEach((currentAnswer, answerNumber) => {
          // ...add an HTML radio button
          answers.push(
            `<label>
              <input type="radio" name="question${questionNumber}" value="${currentAnswer[0]}">
                ${currentAnswer[1]}
            </label>`
          );
        });

        // add this question and its answers to the output
        var re = new RegExp(currentQuestion.highlight,"g")
        var replace_txt = "<b>$&</b>"
        var question_txt = currentQuestion.question.replace(re, replace_txt )
        output.push(
          `<div class="slide">
            第${questionNumber+1}/${myQuestions.length}题
            <div class="question"> ${question_txt} </div>
            <div class="answers"> ${answers.join("")} </div>
            <div class="translation" style="color:#f8f6f0"> 翻译：${currentQuestion.translation} </div>
            <form id="testresultform${questionNumber}" action="/doublesyllable/${currentQuestion.id}/result/" method="post">
                {% csrf_token %}
                <input type='hidden' name="test_answer" value="" />
                <input type='hidden' name="test_result" value="" />
            </form>
          </div>`
        );
      });

      // finally combine our output list into one string of HTML and put it on the page
      quizContainer.innerHTML = output.join("");
    }

    function nextWord() {
      location.reload();
    }

    function showResults() {
      // gather answer containers from our quiz
      const answerContainers = quizContainer.querySelectorAll(".answers");
      // gather translation container from our quiz
      const translationContainers = quizContainer.querySelectorAll(".translation");

      // keep track of user's answers
      let numCorrect = 0;

      // for each question...
      myQuestions.forEach((currentQuestion, questionNumber) => {
        // find selected answer
        const answerContainer = answerContainers[questionNumber];
        const selector = `input[name=question${questionNumber}]:checked`;
        const userAnswer = (answerContainer.querySelector(selector) || {}).value;
        var is_correct = 0

        // if answer is correct
        if (userAnswer === currentQuestion.correctAnswer) {
          // add to the number of correct answers
          numCorrect++;

          // color the answers green
          answerContainers[questionNumber].style.color = "green";
          translationContainers[questionNumber].style.color = "green";
          //
          is_correct = 1
        } else {
          // if answer is wrong or blank
          // color the answers red
          answerContainers[questionNumber].style.color = "red";
          translationContainers[questionNumber].style.color = "red";
        }

        // set test result form data
        document.getElementsByName('test_answer')[questionNumber].value = userAnswer
        document.getElementsByName('test_result')[questionNumber].value = is_correct

        // submit test result to server
        $('#testresultform'+questionNumber).submit(function(e) {

          e.preventDefault(); // avoid to execute the actual submit of the form.

          var form = $(this);
          var url = form.attr('action');

          $.ajax({
                method: "POST",
                url: url,
                data: form.serialize(), // serializes the form's elements.
                }).done(function(data)
                {
                  console.log('Submission was successful.');
                  console.log(data);
                }).fail(function (data) {
                  console.log('An error occurred.');
                  console.log(data);
                });
        });
        
        $('#testresultform'+questionNumber).submit();

      });

      // show number of correct answers out of total
      resultsContainer.innerHTML = `共 ${myQuestions.length} 题，答对 ${numCorrect} 题`;
      {% if not hide_next_word %}
      if (numCorrect === myQuestions.length) {
        nextWordButton.style.display = "inline-block"
      }
      {% endif %}
    }

    function showSlide(n) {
      slides[currentSlide].classList.remove("active-slide");
      slides[n].classList.add("active-slide");
      currentSlide = n;

      if (currentSlide === 0) {
        previousButton.style.display = "none";
        nextWordButton.style.display = "none";
      } else {
        previousButton.style.display = "inline-block";
      }

      if (currentSlide === slides.length - 1) {
        nextButton.style.display = "none";
        submitButton.style.display = "inline-block";
      } else {
        nextButton.style.display = "inline-block";
        submitButton.style.display = "none";
      }
    }

    function showNextSlide() {
      showSlide(currentSlide + 1);
    }

    function showPreviousSlide() {
      showSlide(currentSlide - 1);
    }

    const quizContainer = document.getElementById("quiz");
    const resultsContainer = document.getElementById("results");
    const submitButton = document.getElementById("submit");
    const nextWordButton = document.getElementById("nextword");

    // display quiz right away
    buildQuiz();

    const previousButton = document.getElementById("previous");
    const nextButton = document.getElementById("next");
    const slides = document.querySelectorAll(".slide");
    let currentSlide = 0;

    showSlide(0);

    // on submit, show results
    submitButton.addEventListener("click", showResults);
    previousButton.addEventListener("click", showPreviousSlide);
    nextButton.addEventListener("click", showNextSlide);
    nextWordButton.addEventListener("click", nextWord);
  })();


</script>
{% else %}
    {% if total_words %}
    <p>您已完成所有双音词的{{ title }}.</p>
    {% else %}
    <p>您没有词语需要学习.</p>
    {% endif %}
    <a href="/doublesyllable/">返回</a>
{% endif %}
</body>

</html>